kind: pipeline
type: docker
name: Build

platform:
  os: linux
  arch: arm64

steps:

# Create and run the Restaurant server
  - name: Create Server Image
    image: docker 
    volumes:
      - name: dockerSocket
        path: /var/run/docker.sock
    commands:
      - cd server
      - docker buildx build --no-cache --load -t restaurant-search-server:latest -f Dockerfile-local .
      - docker run -p 5001:5001 -d restaurant-search-server:latest

# Create and run the Restaurant Client

  - name: Create Client Image
    image: docker
    volumes:
      - name: dockerSocket
        path: /var/run/docker.sock
    commands:
      - cd client
      - docker buildx build --no-cache --load -t restaurant-search-client:latest -f Dockerfile-local .
      - docker run -p 3000:80 -d restaurant-search-client:latest

volumes:
  - name: dockerSocket
    host:
      path: /var/run/docker.sock